### PR TITLE
Experimental PR

### PR DESCRIPTION
**Pull request by SlNPacifist**
I've added scripts to collect dependent files. They use g++ to collect all dependencies. Scripts needs to be changed since they contain my local file paths and I'm not good at writing shell scripts.

I've extracted all needed files from llvm/lldb from branches release_38, release_39 and master as three different commits to be able to compare them easily. Previous releases do not compile with current bindings.

Updated build.rs to be linux and mac friendly. Did not check this on mac.

What could be done: checkout dependent files and generate c bindings for most common versions of lldb met in different OS (versions of last two years). In build.rs check latest version of lldb installed on current pc and use appropriate files to compile lib.

### CODE REVIEW

**Comment by SlNPacifist** [comment]
I guess we could do something like this: https://github.com/KyleMayes/clang-sys/blob/master/build.rs in order to support cross-platform building.

**Comment by waywardmonkeys** [comment]
Okay ... on Linux, can you use `llvm-config` to get the info for `lldb` and what name to link against?

As for headers, I'd like to end up just requiring a relatively current version for now, so I'm okay with using the headers from 3.8 and updating in the future.

I have a couple of things to submit upstream to the LLDB project, but didn't do it in time for the 3.9 release. :(

**Comment by waywardmonkeys** [comment]
And can you use `cfg!` to get the target info rather than the `TARGET` environment variable?

**Comment by SlNPacifist** [comment]
Seems like `llvm-config` does not know anything about `lldb`. However, it could tell me path to header files and path to library files:

```
$ llvm-config --includedir
/usr/lib/llvm-3.8/include
$ llvm-config --libdir
/usr/lib/llvm-3.8/lib
```

All needed header files are in `/usr/lib/llvm-3.8/include` and I was able just to replace my `external` folder with it and successfully compile `lldb-sys`.
`/usr/lib/llvm-3.8/lib` contains `liblldb.so`, however it is a broken link. This looks like a package problem on Ubuntu.
With broken link I am able to add `/usr/lib/llvm-3.8/lib` folder to search paths and build working crate with `lldb-3.8` library. Once I fixed the link, I was able to build working crate with `lldb` library.

> And can you use cfg! to get the target info rather than the TARGET environment variable?

Sure, just copied code from somewhere. I'm not really used to code such low-level things.

I'll make new PR after you tell how to work around broken `liblldb.so` link in ubuntu. Variant that I see:
- link to `lldb` library and just make a note about a possible problem in readme
- get a version from `llvm-config` and link to specific version
- try to check for several library names and pick first that exists

Maybe there is a better solution for this.

**Comment by waywardmonkeys** [comment]
For now, let's go with "get a version from `llvm-config` and link to specific version" ... Okay?

And if you can, report the broken link upstream?

**Comment by SlNPacifist** [comment]
> And if you can, report the broken link upstream?

Where should I report it? To ubuntu package maintainers or to https://llvm.org/bugs/ or somewhere else?

**Comment by waywardmonkeys** [comment]
I'd start with Ubuntu's package maintainers.

**Comment by waywardmonkeys** [comment]
Now that the other PR (#4) has landed, is anything from here needed?

**Comment by SlNPacifist** [comment]
Nope, this is experimental PR and can be deleted.

**Pull request closed without merging**
